### PR TITLE
[REFACTOP] beautify interface

### PR DESCRIPTION
**Pull request by carlenee**
I changed the payment options in the landing page 
before:
image
after:
image
to match the components in the /package page

I also changed the loader in the create event page so that it doesnt overlap with the planning button to a loader that we use in every page for consistency

### CODE REVIEW

**Review by JohannesSetiawan — APPROVED** [review]
LGTM!

**Review by catherineeangel — APPROVED** [review]
Nice addition!

**Review by nataniadeandra — APPROVED** [review]
Nice change! This makes our website much more consistent.

**Review by emiriko — CHANGES_REQUESTED** [review]
Hi Carlene, good job on beautifying our frontend. I have one request, and I think this would make that interface super nice looking.

I think the top right border radius and bottom right radius should be removed right? Because we want to make it feel as if the package are combined. This is what i meant

image

**Comment by carlenee** [comment]
> Hi Carlene, good job on beautifying our frontend. I have one request, and I think this would make that interface super nice looking.
> 
> I think the top right border radius and bottom right radius should be removed right? Because we want to make it feel as if the package are combined. This is what i meant
> 
> image

image
done!

**Review by emiriko — APPROVED** [review]
Thank you for the changes, Nice! LGTM.

**Pull request merged**
