### PR TITLE
PBI: Loading State

### PR DESCRIPTION
**Pull request by swastikanata**
What I did for this merge request:

- Adding loading state when creating step and rundown with AI
- Adding loading state when updating profile
- Adding loading state when creating and updating venue and vendor

### CODE REVIEW

**Review by JohannesSetiawan — APPROVED** [review]
LGTM!

**Review by emiriko — APPROVED** [review]
LGTM!

**Review by nataniadeandra — APPROVED** [review]
Nice improvement!

**Review by catherineeangel — APPROVED** [review]
LGTM. This is what we needed.

**Pull request merged**
