### PR TITLE
Feat: Integrate create steps with AI

### PR DESCRIPTION
**Pull request by catherineeangel**
In this PR, I have integrated the BE of create steps with AI. 
The flow of this feature:
1. User goes to task detail page
2. Task detail has no steps yet
3. Shows an option of creating manually or creating with ai
4. user clicks create with ai button
5. AI generates answer and redirect to create steps form
6. User can update and/or delete the steps and also add if they want to
7. User saves the steps
8. User will be directed back to the task detail page with the newly created steps.

### CODE REVIEW

**Review by JohannesSetiawan — APPROVED** [review]
Good job in creating and testing this feature. LGTM

**Review by JohannesSetiawan — CHANGES_REQUESTED** [review]
Might want to check first whether the provideTags and invalidateTasg in task detail APi really works as intended (when a user edit a step name/desc, it immediately updated on the fornt end)

**Review by JohannesSetiawan — APPROVED** [review]

**Review by emiriko — CHANGES_REQUESTED** [review]
Great implementation, but it appears that there is a conflict between your branch and staging. It would be nice for you to handle the conflict first.

**Comment by catherineeangel** [comment]
> Great implementation, but it appears that there is a conflict between your branch and staging. It would be nice for you to handle the conflict first.

Right, I have fixed it now. Thank you for the notice

**Review by emiriko — APPROVED** [review]
LGTM now!

**Pull request merged**
