### PR TITLE
Implemented locked AI button for non-premium users

### PR DESCRIPTION
**Pull request by nataniadeandra**
**Change made:**
Enhancements have been made to the user interface for non-premium users. Specifically, an AI button has been introduced which appears in a 'locked' state. This visual cue is designed to clearly communicate that certain features are exclusive to premium users. This change aims to improve user understanding and friendliness of the platform, as opposed to the previous design where the distinction between premium and non-premium features was not as clear.

**Image:**
image

### CODE REVIEW

**Review by catherineeangel — APPROVED** [review]
LGTM

**Review by JohannesSetiawan — APPROVED** [review]
LGTM!

**Review by emiriko — APPROVED** [review]
Very nice, one question though? Do you use additional package from third party. If you do, what is it? And what's the thought behind it? Isn't material UI have disabled button as well? If you didn't, why is there so much changes on `package.lock.json`?

**Comment by nataniadeandra** [comment]
Hi, @emiriko,

I previously attempted to use a lock icon which required the `@emotion/styled` library. However, I encountered a dependency issue. So, I deleted the `node_modules` folder and `package-lock.json`, and reran `npm install`. Despite only adding and updating two libraries, rerunning the installation caused significant differences in the `package-lock.json`.

I eventually found a better icon in the Phosphor icon library, which doesn't require `@emotion/styled`. Below are the libraries I mentioned:

IMG_3806

**Pull request merged**
