### PR TITLE
PBI Membuat Timeline

### PR DESCRIPTION
**Pull request by catherineeangel**
In this PR, I have added "add to timeline" icon button shown with a calendar and plus icon in task step so user can integrate it to the event's timeline. When the task step is not yet integrated in timeline, then the button will be available, otherwise it is not available. The timeline date will be visible in the stepper description and visible when the user is on the active step.
When the button is clicked, the user can fill in the start and end date time.
There is also validation to make sure the dates did not overlap/
Screenshot 2024-05-04 at 09 25 22
Screenshot 2024-05-04 at 09 43 06

Screenshot 2024-05-04 at 09 34 57

Screenshot 2024-05-04 at 09 27 33
Screenshot 2024-05-04 at 09 44 24

### CODE REVIEW

**Review by JohannesSetiawan — CHANGES_REQUESTED** [review]
The code and the UI seems good, but it seems there's some bugs as detected on the SonarCloud and your branch conflict with the staging branch. Might want to fix that first.

**Review by JohannesSetiawan — APPROVED** [review]
LGTM!

**Review by carlenee — APPROVED** [review]
LGTM! Good Job

**Review by nataniadeandra — APPROVED** [review]
LGTM!

**Pull request merged**
