### PR TITLE
Pbi mengelola event

### PR DESCRIPTION
**Pull request by emiriko**
What I have changed:

- Adding mutations to create events
- Implementing those mutations on my components and testing them
- Adding a loading state button and toast for better interactivity
- Creating detail event page
- Adding redirection after making the event
- Creating a chips for different event detail options

What to do next:
- Creating more tests for detail event page.
- Revamping UI on detail event page.

### CODE REVIEW

**Review by catherineeangel — COMMENTED** [review]
Please add description on what you add on this PR

**Review by catherineeangel — APPROVED** [review]
LGTM.

**Review by JohannesSetiawan — APPROVED** [review]
Great job implementing the create events feature. The code and the testing looks good. LGTM

**Comment by emiriko** [comment]
Thank you for all the feedback, it has been implemented. I will merge it now.

**Pull request merged**
